### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by themikkoh** [ZakarFin/mm-hsl-timetable#4]
Can't get this work. Any ideas? I am just started with this MagicMirror... So basically I just copied the files under modules/mm-hsl-timetable and added this to config.js:
{
	module: "mm-hsl-timetable",
	position: "top_right",
	header: "Bus schedule",
	config: {
		stops: [1130113],
		busCount: 5
	}
},

**Comment by ZakarFin** [comment]
Did you get it to work?

**Comment by themikkoh** [comment]
Yes, noticed that I cant just download the files. Needed to do those .js files.
