### ISSUE TITLE
Create package.json

### ISSUE THREAD

**Issue by KristjanESPERANTO** [ZakarFin/mm-hsl-timetable#5]
I am working on a new module list, which you can see [here](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/). If you search for your module in it, you will see that it looks a bit bland at the moment, as a screenshot and tags are missing.

You can change that by adding a `package.json` file. The information that is currently used from that file is the license information (the screenshot can only be displayed if the license is free) and the keywords (these are then displayed as tags).

[Here is an example of a package.json](https://github.com/Jacopo1891/MMM-RandomQuotes/blob/master/package.json).

I recommend using the keyword "Public Transport", because it's like a main category.

It would be nice if you would add the file to your repository :slightly_smiling_face:

**Comment by ZakarFin** [comment]
Nice work doing the listing :) I added a simple package.json for now. I haven't updated this in a bit but when I do I saw you had some other notes as well that I need to look at:
https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/blob/main/result.md#mm-hsl-timetable-by-zakarfin

- There is no package.json. We need this file to gather information about the module for the module list page.
- Recommendation: Module name doesn't follow the recommended pattern (it doesn't start with MMM-). Consider renaming your module.
- Typo: Found Magic Mirror in file mm-hsl-timetable.js: Replace it with MagicMirror².
- Recommendation: Found "node-fetch" in file node_helper.js: Replace it with built-in fetch.
- Recommendation: Found new Date() in file node_helper.js: Replace it by new Date(Date.now()): https://github.com/MagicMirrorOrg/MagicMirror/issues/3252.
- Warning: No LICENSE file.
- Recommendation: No ESLint configuration was found. ESLint is very helpful, it is worth using it even for small projects.
- The branch name is 'master'. Consider renaming it to 'main'.

Also the digitransit API now requires an API key. I'll need to add some notes on how to get one (it's free, but needs to be done for this to work).

**Comment by KristjanESPERANTO** [comment]
Nice! With the package.json your module now looks nice on the new module list :rocket: 

The other points are additional recommendations and not relevant for the list.

Yeah, would be nice if you could write how to get an API key in the README.

Thanks for creating and maintaining this module! :smiley:

**Comment by ZakarFin** [comment]
Added support and documentation for APIkeys in https://github.com/ZakarFin/mm-hsl-timetable/pull/6
